spring:
  application:
    name: bus-ticket-system

  datasource:
    url: jdbc:mysql://localhost:3306/bus_ticket_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 143323
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin123

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
